In [14]:
import numpy as np
import random

In [190]:
class RBF:
    def __init__(self, radial_neurons_num = 3):
        self._radial_neurons_num = radial_neurons_num
        self._w = None
        self._c = None
    def activation_function(self, x, c):
        return np.exp(-(x-c)**2)
    
    def _set_weights(self, x, y):
        c = random.sample(list(x),k= self._radial_neurons_num)
        c = np.array(c, ndmin=2).T
        act = self.activation_function(x,c).reshape(-1, self._radial_neurons_num)
        self._w = np.dot(np.linalg.pinv(act), y)
    
    def _forward_progation(self, x,y):
        xd = x * self._w
        print(xd)
        return self.activation_function(x,y)

In [191]:
x = np.linspace(-1,1,50)
y = np.sin((x+0.5)**3) + np.random.uniform(-0.1, 0.1)

In [192]:
rbf = RBF(4)

In [193]:
rbf._set_weights(x,y)

In [194]:
yd = rbf._forward_progation(x[1], y[1])

[-20.58698116  20.25453838  23.03714174 -23.14023961]


In [195]:
yd

0.4871893716117641

In [188]:
yd.sum()

0.4157815232271528

In [189]:
y[1]

-0.02238308570873873

In [45]:
c=np.array([1,2])

In [53]:
xd =np.exp(-(x-np.array([0,1,2], ndmin=2).T)**2)

In [63]:
xd.reshape(-1,3)[40]

array([0.00849371, 0.01013423, 0.01205139])

array([[0],
       [1],
       [2]])